export const projectData = [
  {
    id: 1,
    name: '마이날자',
    date: '2024.09 - 2024.10',
    shortIntro: '커리어 역량 진단 및 분석, 코칭을 제공하는 사내 역량 강화 서비스',
    dev: [
      'MBTI검사와 비슷한 커리어 역량 진단 서비스 MVP 웹 프론트 개발',
      '계약된 기업을 관리하는 마스터 웹 프론트 개발',
      'Recoil을 사용해 유저정보, 진단종류에 따른 설문 전역 상태 관리',
      'MUI 커스터 마이징을 통한 UI 개발',
    ],
    skill: 'NextJS, TypeScript, Recoil, Axios, MUI, React-Beautiful-DND, XLSX, AWS EC2, Docker',
    ui: 'https://www.notion.so/UI-12a2355dd81d80809f97d233d14fbf40',
  },
  {
    id: 2,
    name: '(주)레이드 - 핏엔드',
    date: '2023.05 - 2024.05',
    shortIntro:
      '온/오프라인 코칭으로 회원분들이 지속적인 운동습관을 형성할 수 있는 FITEND라는 브랜드의 서비스를 제공',
    dev: [
      '사내 트레이너들이 사용하는 트레이너 전용 웹 프론트 개발',
      '회원, 트레이너의 데이터를 관리하는 마스터 웹 풀스택 개발',
      '회원, 트레이너, 수강권 등 CRUD 개발',
      '운동 영상 업로드 및 업로드 된 영상 canvas를 이용해 썸네일 생성',
      'React-Beautiful-DND를 사용해 운동 순서 변경 UX/UI 개발',
      'FullCalendar를 커스텀하여 자체 캘린더에서 트레이너의 스케줄 및 회원 운동 스케줄 관리',
      'MUI 커스터 마이징을 통한 UI 개발',
    ],
    skill:
      'NextJS, TypeScript, NodeJS, Express, MySQL, FullCalendar, React-Beautiful-DND, MUI, AWS EC2, Docker',
    ui: 'https://www.notion.so/UI-13c2355dd81d801d9a49ccdaaa0247b4',
  },
  {
    id: 3,
    name: '데일리 클럽',
    date: '2022.09 - 2022.10',
    shortIntro: '일회성 동호회를 모집하고 참여할 수 있는 서비스를 제공',
    dev: [
      '프론트엔드 3인, 백엔드 2인, 디자인 1인으로 구성된 팀에서 프론트엔드 팀장 담당',
      'Styled-Components를 활용하여 재사용 컴포넌트 개발',
      '일회성 모임에 대한 CRUD 구현',
      '구성원의 친절도 (당근 마켓 온도)에 따른 신청 제한 개발',
      '신청, 취소, 삭제 confirm 모달 개발',
    ],
    skill: 'React, React-Router-Dom, Styled-Components, Axios, TypeScript, AWS(S3)',
    github: 'https://github.com/cjsgmail/dailyclub',
    blog: 'https://velog.io/@cjs0097/series/Main-Project',
  },
  {
    id: 4,
    name: '네이버 OPEN API',
    date: '2022.07',
    shortIntro: '네이버 쇼핑 API를 불러오기 학습',
    dev: [
      'proxy 설정을 통해 CORS에러 해결',
      'input 자동 포커스 구현',
      'flex box 학습',
      '블로그 3900뷰',
    ],
    skill: 'React, Axios, Naver Open API',
    github: 'https://github.com/cjsgmail/naver-shopping',
    blog: 'https://velog.io/@cjs0097/%EB%84%A4%EC%9D%B4%EB%B2%84-%EC%87%BC%ED%95%91-%EA%B2%80%EC%83%89-API-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0',
  },
  {
    id: 5,
    name: '고양이 MBTI',
    date: '2022.06',
    shortIntro: '리액트를 처음 학습할 때 개발한 고양이 MBTI',
    dev: ['react 학습', 'react-router-dom 학습', 'styled-components 학습'],
    skill: 'React, Styled-Components, Vercel',
    github: 'https://github.com/cjsgmail/catmbti',
    url: 'https://catmbti-two.vercel.app/',
  },
]
